spring:
  application:
    name: service
  datasource:
    url: "jdbc:postgresql://localhost:5432/userdb"
    username: postgres
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      # We should rather use Flyway. But for simplicity, here rely
      # on Hibernate to handle the schema (which is usually not a good idea).
      ddl-auto: "none"


eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 0

