spring:
  application:
    name: Gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: service
          # "lb" stands for Load-Balance, which is done with Ribbon
          uri: lb://service
          predicates:
            - Path=/service/**
          filters:
            - StripPrefix=1
        - id: frontend
          uri: http://frontend
          predicates:
            - Path=/**


eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
